#Deriving the latest base image
FROM python:latest

#Labels as key value pair
LABEL Maintainer="anurag.1997"

# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
WORKDIR /home/godkira/ds_project/Monitor

#to COPY the remote file at working directory in container
COPY heartbeat_check.py ./
COPY requirements.txt ./
# Now the structure looks like this '/usr/app/src/test.py'

# Install required dependencies
RUN apt-get update && apt-get install -y wget python3-pip

# Install Miniconda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh \
    && bash miniconda.sh -b -p /opt/conda \
    && rm miniconda.sh

# Set environment variables
ENV PATH="/opt/conda/bin:${PATH}"

RUN conda update -n base -c defaults conda && conda install -c conda-forge -y liblsl

# Install any needed dependencies specified in requirements.txt
RUN pip install paho-mqtt
RUN conda install -c conda-forge paho-mqtt

#CMD instruction should be used to run the software
#contained by your image, along with any arguments.

ENTRYPOINT [ "python", "./heartbeat_check.py"]